### ISSUE TITLE
Proposal > adaptative Client constructor

### ISSUE THREAD

**Issue by tzi** [KnpLabs/PiwikClient#4] opened 2013-11-06 23:01 UTC
Hi!

This is a proposal. If you accept it on the principle, I will make a PR with the updated code, tests & docs.

---

I propose to introduce more polymorphism in the Client instantiation:

``` php
use \Knp\PiwikClient\Client;

// Exactly what you want
new Client($connection, $apiToken);
// Your connection with an anonymous use of API
new Client($connection);
// A HttpConnection
new Client($apiURL, $apiToken);
// A HttpConnection with an anonymous use of API
new Client($apiURL);
// A PiwikConnection (local PHP instance)
new Client();
```

This will simplify the use of the library & make an awesome example for the README.

Cheers,
Thomas.

**Comment by inoryy** [comment] 2013-11-12 12:15
I'm not sure it's a good idea to have so many different variations under same constructor. What's the use case?

Maybe in a form of a wrapper instead? i.e. 

``` php
new LocalClient(); // A PiwikConnection (local PHP instance)
```

**Comment by tzi** [comment] 2013-11-12 13:34
Hi @Inori!

I've not change much.
I just added that the connection argument could be null or a string.

The usecase is to make the use of this library simpler & more readable.
Before:

``` php
use Knp\PiwikClient\Connection\HttpConnection;
use Knp\PiwikClient\Client;

// Instantiate piwik client
$connection = new HttpConnection('http://demo.piwik.org');
$client = new Client($connection, 'YOUR_API_TOKEN');

// Call piwik API
$array = $client->call('PLUGIN.METHOD', $parameters);
```

After:

``` php

// Instantiate piwik client
use Knp\PiwikClient\Client;
$client = new Client('http://demo.piwik.org', 'YOUR_API_TOKEN');

// Call piwik API
$array = $client->call('PLUGIN.METHOD', $parameters);
```

It seems more like what I expected to write.
Note: it is mainly for the README & the developers that do not use dependency injection.

I find it enough readable to not need a wrapper class, but it is my opinion.

See you,
Thomas.

**Comment by docteurklein** [comment] 2014-08-19 14:48
the problem is that you lose flexibility, by not having control anymore on the http connection.
Even if you could, it complicates the api signature, which isn't a good thing imho.

closing for now.

**Closed as completed by docteurklein** 2014-08-19 14:48 UTC
